/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsua_appJNI {
  public final static native int initApp();
  public final static native void deinitApp();
  public final static native int startPjsua(String jarg1);
  public final static native void setInput(String jarg1);
  public final static native String getMessage();
  public final static native void finishDisplayMsg();
}
