/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsua_app {
  public static int initApp() {
    return pjsua_appJNI.initApp();
  }

  public static void deinitApp() {
    pjsua_appJNI.deinitApp();
  }

  public static int startPjsua(String cfgFile) {
    return pjsua_appJNI.startPjsua(cfgFile);
  }

  public static void setInput(String s) {
    pjsua_appJNI.setInput(s);
  }

  public static String getMessage() {
    return pjsua_appJNI.getMessage();
  }

  public static void finishDisplayMsg() {
    pjsua_appJNI.finishDisplayMsg();
  }

}
