
#define ENABLE_SIP_TCP 1
//#define ENABLE_SIP_TLS  1
#define PJ_HAS_TCP 1
//#define PJ_HAS_SSL_SOCK 1
//#define PJSIP_HAS_TLS_TRANSPORT 1

#define PJMEDIA_HAS_BCG729		1
#define BCG729_STATIC
#define PJMEDIA_AUDIO_DEV_HAS_WASAPI 0
#define PJMEDIA_AUDIO_DEV_HAS_WMME 0
#define PJMEDIA_AUDIO_DEV_HAS_PORTAUDIO 1
