#define PJMEDIA_AUDIO_DEV_HAS_ALSA      1
#define PJMEDIA_AUDIO_DEV_HAS_PORTAUDIO 0
#define PJMEDIA_HAS_VIDEO               0
#define PJMEDIA_WEBRTC_AEC_USE_MOBILE   0
#define PJMEDIA_HAS_SPEEX_AEC   0
#define PJMEDIA_HAS_WEBRTC_AEC   1
